version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    container_name: agnostic_web
    ports:
      - "5001:5001"
    volumes:
      - ./web_src:/app
    links:
      - redis
      - vault
      - postgres

  redis:
    image: redis:latest
    container_name: agnostic_queue
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '511'

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: agnostic_app
    volumes:
      - ./app_src:/app
    environment:
      - VAULT_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID}
    links:
      - redis
      - vault
      - postgres

  vault:
    image: vault:latest
    container_name: agnostic_vault
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    ports:
      - 8200:8200
    environment:
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-config.json

  postgres:
    image: postgres:latest
    container_name: agnostic_rdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./datastore/conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./datastore/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=agnostic
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
