version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    container_name: agnostic_web
    ports:
      - "5001:5001"
    volumes:
      - ./web_src:/app
      - ./certs:/certs
    links:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: agnostic_queue
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '511'

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: agnostic_app
    volumes:
      - ./app_src:/app
      - $HOME/.ssh:/root/.ssh
    environment:
      - BASE_URL=${BASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    links:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    container_name: agnostic_rdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./datastore/conf/postgres.conf:/etc/postgresql/postgresql.conf
      - ./datastore/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=agnostic
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
