FROM python:3

WORKDIR /app

COPY ./web_src/requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 5001

VOLUME /app

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "5001", "--reload", "event_web:app"]
