version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    container_name: agnostic_web
    ports:
      - "5001:5001"
    volumes:
      - ./web_src:/app
    links:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
